param(
    [ValidateSet("Pico", "PicoSt7789", "PicoDvi", "Windows")]
    [string]$Platform
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Platform)) {
    Write-Host "Wybierz platforme docelowa i typ ekranu:"
    Write-Host "  1. Windows"
    Write-Host "  2. Raspberry Pi Pico 2 - ST7789"
    Write-Host "  3. Raspberry Pi Pico 2 - DVI"
    $selection = Read-Host "Wariant [1/2/3]"

    $Platform = switch ($selection.Trim()) {
        "1" { "Windows" }
        "2" { "PicoSt7789" }
        "3" { "PicoDvi" }
        default { throw "Nieprawidlowy wybor '$selection'. Wybierz 1, 2 albo 3." }
    }
}

$target = switch ($Platform) {
    "Windows" {
        @{
            CMakePlatform = "WINDOWS"
            PicoDisplay = "ST7789"
            Label = "Windows"
        }
    }
    "PicoDvi" {
        @{
            CMakePlatform = "PICO"
            PicoDisplay = "DVI"
            Label = "Raspberry Pi Pico 2 - DVI"
        }
    }
    default {
        # "Pico" remains an alias for ST7789 for existing build scripts.
        @{
            CMakePlatform = "PICO"
            PicoDisplay = "ST7789"
            Label = "Raspberry Pi Pico 2 - ST7789"
        }
    }
}

$repositoryRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
$cmakeListsPath = Join-Path $repositoryRoot "CMakeLists.txt"

$common = @'
# == DO NOT EDIT THE FOLLOWING LINES for the Raspberry Pi Pico VS Code Extension to work ==
if(WIN32)
    set(USERHOME $ENV{USERPROFILE})
else()
    set(USERHOME $ENV{HOME})
endif()
set(sdkVersion 2.3.0)
set(toolchainVersion 15_2_Rel1)
set(picotoolVersion 2.3.0)
set(picoVscode ${USERHOME}/.pico-sdk/cmake/pico-vscode.cmake)
if (EXISTS ${picoVscode})
    include(${picoVscode})
endif()
# ====================================================================================
# This file is generated by tools/select_platform.ps1. Do not edit it directly.
cmake_minimum_required(VERSION 3.13)

set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

option(EUZEBIA3D_BUILD_APP "Build the Euzebia3D demo executable" ON)
option(EUZEBIA3D_TEXTURE_CACHE_ENABLED "Enable renderer texture cache for small textures" ON)
option(EUZEBIA3D_TEXTURE_CACHE_FROM_FLASH "Allow renderer texture cache for textures stored in flash/XIP" OFF)
option(EUZEBIA3D_DEBUG_STAGE_ENABLED "Enable volatile *_debug_stage markers for debugger tracing" OFF)
option(EUZEBIA3D_RENDERER_SHADING_ENABLED "Enable renderer per-pixel lighting/shading" ON)
option(EUZEBIA3D_RENDERER_TEXTURE_FILTER_2X2_ENABLED "Enable renderer 2x2 texture filtering" OFF)
option(EUZEBIA3D_RENDERER_PERSPECTIVE_CORRECT_UV_ENABLED "Enable perspective-correct texture coordinates" OFF)
option(EUZEBIA3D_RENDERER_SCENE_SORT_ENABLED "Enable scene triangle depth sorting before rasterization" ON)
option(DEBUG_MODE "Show metrics on the display" ON)
'@

$pico = @'

option(EUZEBIA3D_USE_PSRAM "Enable optional PSRAM-backed const asset copies" ON)
option(EUZEBIA3D_TEXTURE_CACHE_FROM_PSRAM "Allow renderer texture cache for textures stored in PSRAM/XIP" ON)

# Raspberry Pi Pico VS Code extension settings.
if(WIN32)
    set(USERHOME $ENV{USERPROFILE})
else()
    set(USERHOME $ENV{HOME})
endif()
set(sdkVersion 2.3.0)
set(toolchainVersion 15_2_Rel1)
set(picotoolVersion 2.3.0)
set(PICO_EXTRAS_FETCH_FROM_GIT ON)
set(picoVscode ${USERHOME}/.pico-sdk/cmake/pico-vscode.cmake)
if(EXISTS ${picoVscode})
    include(${picoVscode})
endif()

set(PICO_BOARD pico2 CACHE STRING "Board type")
include(pico_sdk_import.cmake)
include(pico_extras_import.cmake)

project(Euzebia3D C CXX ASM)
pico_sdk_init()

add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/libs" "${CMAKE_CURRENT_BINARY_DIR}/pico_libs")

if(EUZEBIA3D_BUILD_APP)
    add_executable(Euzebia3D Euzebia3D.c)
    target_compile_definitions(Euzebia3D PRIVATE EUZEBIA3D_PLATFORM_PICO=1)
    if(DEBUG_MODE)
        target_compile_definitions(Euzebia3D PRIVATE EUZEBIA3D_DEBUG_MODE=1)
    endif()
    if(EUZEBIA3D_DEBUG_STAGE_ENABLED)
        target_compile_definitions(Euzebia3D PRIVATE EUZEBIA3D_DEBUG_STAGE_ENABLED=1)
    endif()

    pico_set_program_name(Euzebia3D "Euzebia3D")
    pico_set_program_version(Euzebia3D "1.0.0")
    pico_generate_pio_header(Euzebia3D ${CMAKE_CURRENT_LIST_DIR}/blink.pio)
    pico_enable_stdio_uart(Euzebia3D 1)
    pico_enable_stdio_usb(Euzebia3D 1)

    target_include_directories(Euzebia3D PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}
        ${CMAKE_CURRENT_LIST_DIR}/storage
    )
    target_link_libraries(Euzebia3D
        pico_stdlib
        pico_multicore
        hardware_spi
        hardware_i2c
        hardware_dma
        hardware_pio
        hardware_interp
        Euzebia3D_libs
    )
    pico_add_extra_outputs(Euzebia3D)
endif()
'@

$windows = @'

project(Euzebia3D C)

set(EUZEBIA3D_APP_MAIN "${CMAKE_CURRENT_LIST_DIR}/Euzebia3D.c")
if(NOT EXISTS "${EUZEBIA3D_APP_MAIN}")
    message(FATAL_ERROR "Missing app main file: ${EUZEBIA3D_APP_MAIN}")
endif()
if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/libs/CMakeLists.txt")
    message(FATAL_ERROR "Missing libraries in ${CMAKE_CURRENT_LIST_DIR}/libs")
endif()
if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/storage/storage.c")
    message(FATAL_ERROR "Missing storage implementation in ${CMAKE_CURRENT_LIST_DIR}/storage/storage.c")
endif()

find_package(SDL3 CONFIG REQUIRED)
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/libs" "${CMAKE_CURRENT_BINARY_DIR}/windows_libs")

if(EUZEBIA3D_BUILD_APP)
    add_executable(Euzebia3D_PC "${EUZEBIA3D_APP_MAIN}")
    target_include_directories(Euzebia3D_PC PRIVATE
        "${CMAKE_CURRENT_LIST_DIR}"
        "${CMAKE_CURRENT_LIST_DIR}/storage"
    )
    target_compile_definitions(Euzebia3D_PC PRIVATE EUZEBIA3D_PLATFORM_WINDOWS=1)
    if(DEBUG_MODE)
        target_compile_definitions(Euzebia3D_PC PRIVATE EUZEBIA3D_DEBUG_MODE=1)
    endif()
    if(EUZEBIA3D_DEBUG_STAGE_ENABLED)
        target_compile_definitions(Euzebia3D_PC PRIVATE EUZEBIA3D_DEBUG_STAGE_ENABLED=1)
    endif()
    target_link_libraries(Euzebia3D_PC PRIVATE Euzebia3D_libs)
endif()
'@

$defaultPlatform = $target.CMakePlatform
$defaultPicoDisplay = $target.PicoDisplay
$platformStart = @'

# A parent project may set EUZEBIA3D_PLATFORM before add_subdirectory().
# The platform selected by this script is only the standalone-build default.
if(NOT DEFINED EUZEBIA3D_PLATFORM)
    set(EUZEBIA3D_PLATFORM "__DEFAULT_PLATFORM__")
endif()
string(TOUPPER "${EUZEBIA3D_PLATFORM}" EUZEBIA3D_PLATFORM_NORMALIZED)

if(NOT DEFINED EUZEBIA3D_PICO_DISPLAY)
    set(EUZEBIA3D_PICO_DISPLAY "__DEFAULT_PICO_DISPLAY__")
endif()
string(TOUPPER "${EUZEBIA3D_PICO_DISPLAY}" EUZEBIA3D_PICO_DISPLAY_NORMALIZED)

if(EUZEBIA3D_PLATFORM_NORMALIZED STREQUAL "PICO")
'@.Replace('__DEFAULT_PLATFORM__', $defaultPlatform).Replace('__DEFAULT_PICO_DISPLAY__', $defaultPicoDisplay)

$platformMiddle = @'

elseif(EUZEBIA3D_PLATFORM_NORMALIZED STREQUAL "WINDOWS")
'@

$platformEnd = @'

else()
    message(FATAL_ERROR "Unsupported EUZEBIA3D_PLATFORM='${EUZEBIA3D_PLATFORM}'")
endif()
'@

$content = ($common.TrimEnd() + $platformStart + $pico + $platformMiddle + $windows + $platformEnd + [Environment]::NewLine)
[System.IO.File]::WriteAllText($cmakeListsPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "Aktywny wariant: $($target.Label)"
Write-Host "Wygenerowano: $cmakeListsPath"
